### ISSUE TITLE
Readme issue 1

### ISSUE THREAD

**Issue by niemim** [City-of-Helsinki/ml_project_template#12]
Alla löytämäni korjattavat typot sekä joitain kysymyksiä ja ehdotuksia.

1.
Git is commonly used from from
2.
This is not a hard rule, but in general a viable stable solution is far better than one that is optimized but trivial. <- Mitä tarkoittaa trivial tässä kohtaa? Ehkä joku muu termi on sopivampi.
3.
Compose simple functions with the pipe: hiukan vaikealukuinen. Harkitse rakennetta 1. vanha asia 2. uusi asia. Kappalejako.
Python does not have native pipe operator -> mikä >> on?
4.
Our goal is, that each state <- ei pilkkua ennen that-sanaa
5.
Good reproducibility equals to ease of reproducibility. <- equal on tässä verbi, 'to' pois
6.
Bunch of numbers taken from this sequence have properties similar to some taking them from true random distribution <- +epämääräinen artikkeli 'a true random distribution', lisäksi harkinnan mukaan parempi verbi 'sample', 'draw' tms.
7.
For example if you may have a varying number of input sources to read data from at each training round of the algorithm. <- 'may' on ylimääräinen, ja 'for example' erotetaan usein pilkulla muusta virkkeestä. Yleisesti tämä lause tuntuu keskeneräiseltä.
8.
Version control means that you keep track of all changes in your system, in a reversable way <- 'reversible'
9.
The name of the module becomes the name of your repository after installing the template following the instructions below This allows <- piste puuttuu
10.
For example, if you want to create and create many algorithms that are inheritantly different it might be better to separate them in their own notebooks 02a_model1.ipynb and 02b_model2.ipynb. <- ylimääräinen 'create', lisäksi 'inherently'
11.
Onko muotoilu / merkkaus OK seuraavassa kohdassa:
{% include note.html content='If you are using this template for other than city of Helsinki projects, remove the files favicon.ico and company_logo.png from docs/assets/images/.' %} #

**Comment by NuuttiSten** [comment]
Test instruction had links to a fork that was behind upstream master. Fixed, now instructions refer to this repo. These comments are on old documentation and are now irrelevant.
