### ISSUE TITLE
Do not update Python requirements on Docker image build

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/ml_project_template#25]
Currently requirements are updated on Docker build:

https://github.com/City-of-Helsinki/ml_project_template/blob/a47a23ad066c2b37eba184464914d7d9d585946d/Dockerfile#L22

This means container will use dependencies decided at *build time*. This breaks reproducibility and might lead to user confusion. Container might not match repository state then. Fix is to use `pip install -r requirements.txt` directly.

**Comment by nakytoe** [comment]
done
