### ISSUE TITLE
Upgrade nbdev and its dependencies

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/ml_project_template#26]
There's been few changes in nbdev including new version of nbconvert. Let's see how upgrade is possible and what to use from new features.

**Comment by jussiarpalahti** [comment]
Newest version of Nbdev is unchanged as per cleaning notebooks. [I created an issue there](https://github.com/fastai/nbdev/issues/600)

**Comment by nakytoe** [comment]
Upgrade to nbdev v2
