### ISSUE TITLE
API logging

### ISSUE THREAD

**Issue by nakytoe** [City-of-Helsinki/ml_project_template#38]
- Create logging json schema for API, i.e. for each api event what to log (time, process, what happened, input, output, error messages etc.)

- Implement API logging to local sqlite using https://github.com/tiangolo/sqlmodel (no need to use python logger, just write log records straight to sqlite as JSON strings. 

- Implement setting switch for including or omitting data (e.g. prediction inputs and outputs) from logs to avoid privacy issues with personal data

**Comment by manujoha** [comment]
Implemented sqlite logger:  https://github.com/Datahel/mlops_fast_api_poc/pull/3
