### ISSUE TITLE
Add pre-commit hooks to container

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/ml_project_template#42]
As specified [here](https://nbdev.fast.ai/tutorials/pre_commit.html)

Run git hook installation setup either just inside Devcontainer or in Dockerfile as well.

**Comment by jussiarpalahti** [comment]
[As per instructions](https://pre-commit.com/index.html#automatically-enabling-pre-commit-on-repositories) you can't actually force Git repository to use git hooks without user's opt-in. Which is a good thing, I guess. This means, that instructions need to be updated on that topic. Inside dev container I should think installation of Git hooks can be mandatory, so they'll work from inside Codespaces.

**Comment by nakytoe** [comment]
Agree. Dockerfile install was removed because otherwise papermill parameterisation tags were cleaned from the notebooks. Now this should not be an issue

**Comment by nakytoe** [comment]
The template should also be used dockerized by default, whether or not with code spaces
